# Generated by Django 2.1.5 on 2019-03-25 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frontendcontest',
            options={'ordering': ['-start_date']},
        ),
    ]
