# Generated by Django 2.1.5 on 2019-02-14 18:55

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import main.models.problem
import main.models.submission


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('users', models.ManyToManyField(blank=True, related_name='contests', related_query_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('score', models.PositiveIntegerField(default=10)),
                ('selenium_script', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/selenium_scripts', location='/home/sajad/Codavar/codavar/test_scripts/selenium_scripts'), upload_to=main.models.problem.generate_filename)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Contest')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('zip_file', models.FileField(upload_to=main.models.submission.generate_filename)),
                ('judge_score', models.IntegerField(null=True)),
                ('is_final', models.BooleanField(default=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
