# Generated by Django 2.1.5 on 2019-02-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='selenium_script_as_module_string',
            field=models.CharField(default='ss', max_length=500),
            preserve_default=False,
        ),
    ]
