# Generated by Django 2.1.5 on 2019-02-06 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_problem_selenium_script_as_module_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='contests', related_query_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
