# Generated by Django 2.1.5 on 2019-02-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_submission_is_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='score',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
