# Generated by Django 2.1.5 on 2019-03-24 11:39

import apps.submission.models.front_end_submission
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontEndSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to=apps.submission.models.front_end_submission.generate_filename)),
                ('judge_score', models.PositiveIntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FrontEndContestSubmission',
            fields=[
                ('frontendsubmission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='submission.FrontEndSubmission')),
                ('is_final', models.BooleanField(default=False)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.FrontEndContest')),
            ],
            options={
                'abstract': False,
            },
            bases=('submission.frontendsubmission',),
        ),
        migrations.AddField(
            model_name='frontendsubmission',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', related_query_name='submission', to='problem.FrontEndProblem'),
        ),
        migrations.AddField(
            model_name='frontendsubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_frontendsubmissions', related_query_name='submission_frontendsubmission', to=settings.AUTH_USER_MODEL),
        ),
    ]
