# Generated by Django 2.1.5 on 2019-03-25 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frontendcontestsubmission',
            options={'ordering': ['-upload_date']},
        ),
        migrations.AlterModelOptions(
            name='frontendsubmission',
            options={'ordering': ['-upload_date']},
        ),
    ]
