# Generated by Django 2.1.5 on 2019-03-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_frontendsubmission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendsubmission',
            name='judge_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
