# Generated by Django 2.1.5 on 2019-03-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_auto_20190327_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontendsubmission',
            name='judge_score',
        ),
        migrations.AddField(
            model_name='frontendsubmission',
            name='relative_score',
            field=models.FloatField(default=0),
        ),
    ]
