# Generated by Django 2.1.5 on 2019-03-24 11:39

import apps.problem.models.front_end_problem
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontEndProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('statement', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
                ('score', models.PositiveIntegerField(default=1)),
                ('selenium_script', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/judge-script/fe/', location='/home/sajad/Codavar/codavar/test_scripts/selenium_scripts'), upload_to=apps.problem.models.front_end_problem.selenium_script_filename)),
            ],
            options={
                'ordering': ['score'],
            },
        ),
    ]
