# Generated by Django 2.1.5 on 2019-03-22 19:43

import apps.problem.models
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('score', models.PositiveIntegerField(default=10)),
                ('selenium_script', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/selenium_scripts', location='/home/sajad/Codavar/codavar/test_scripts/selenium_scripts'), upload_to=apps.problem.models.generate_filename)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Contest')),
            ],
            options={
                'ordering': ['score'],
            },
        ),
    ]
